blog/urls.py
from django.urls import path, include # include 함수로 landing에 연결을 해줄 수 있음.
from . import views # 상대경로로 저장을 해 줘야 함.

app_name = "blog"
urlpatterns = [
    path('',views.index), # 아무것도 입력안했을 때, views의 index를 실행시켜준다.
    path('second/',views.article),
    path('post-write/', views.blog_post_write),
    path('home/', views.blog_home, name="home"),
    path('post-view/<int:post_id>/', views.blog_post_view, name="detail"),
    path('post-edit/<int:post_id>/', views.blog_post_update),
    path('post-delete/<int:post_id>/',views.blog_post_delete),
]

django_demo/urls.py
from django.contrib import admin
from django.urls import path, include # include 함수로 landing에 연결을 해줄 수 있음.
from django.conf import settings
from django.conf.urls.static import static
from . import views # 상대경로로 저장을 해 줘야 함.


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('landing/',include('landing.urls')),
    path('blog/',include('blog.urls')),
    path('blog_samples/',include('blog_samples.urls')),
    path('my_accounts/', include('my_accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

my_accounts/urls.py
from django.urls import path
from my_accounts import views

app_name='my_accounts'

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name = 'logout')
]

my_accounts/models.py
from django.db import models

# Create your models here.

my_accounts/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import auth
# Create your views here.

def sign_up(request):
    # 요청이 post인지 확인 / 그게 아니라면 get일 것.
    context = {}
    if request.method == 'POST':
    # 1. 요청받은 request에서 username이 존재하는지 &
        username = request.POST.get('username')
    # 2. 요청받은 request에서 userpassword가 존재하는지 &
    # 3. 요청받은 request에서 password와 password_check가 같은지 &
        password = request.POST.get('password')
        password_check = request.POST.get('password_check')
        
        if (username and password and password == password_check):
            try: # error를 잡아주는 python method 'try'
                new_user = User.objects.create_user(username=username, password = password)
                auth.login(request, new_user)
                print('log in success!')
                return HttpResponseRedirect(reverse('blog_samples:home'))
            except:
                context['error'] = '이미 존재하는 id입니다.'
    # all clear = sign up 실행 - new user id로 log in까지 시켜주기.
    # 블로그 홈으로 리다이렉트 시켜주기.
    # 위 조건 중 맞지 않다면, error message를 context에 담기.
        else:
            context['error'] = '아이디와 비밀번호를 잘 못 입력하셨습니다.'
    
     
    return render(request, 'my_accounts/sign_up.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect("blog_samples:home")
    context={}
    # 요청이 post인지 확인
    if request.method == 'POST':
    # id 입력받은 것이 있는지? ok / password 입력받은 것이 있는지? ok 
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        if (username and password):
    # password check? ok --- 추가적으로 필요한 함수
            user = auth.authenticate(
                request,
                username = username, password = password
            )
            if user:
                auth.login(request, user)
        # login ok
                return redirect('blog_samples:home')
        # redirect ok
        
    # all clear > login
            else:
                context['error'] = 'login failed'
    # failed > context에 error message 담아주기.
    else:
        context['error'] = 'put in your id & password'
    
    return render(request, 'my_accounts/login.html', context)

def logout(request):
    # 요청이 post인지 확인!
    # if request.method == "POST":
    auth.logout(request)
    # 로그아웃 o / 
    return redirect('blog_samples:home')
    # redirect o

my_accounts/templates/my_accounts/login.html
{% extends 'base.html' %}

{%block title%}
<title>login page</title>
{%endblock%}

{%block main%}
<h1>This is login page</h1>

{%if error%}
<p>{{error}}</p>
{%endif%}

<form action = "{%url 'my_accounts:login'%}" method = 'post'>
    {%csrf_token%}
<form>
    <div>
        <input name='username' placeholder='put in your id'/>
    </div>
    <div>
        <input type='password' name ='password' placeholder='put in your password'/>
    </div>
    <button type='submit'> log - in </button>
</form>
{%endblock%}

my_accounts/templates/my_accounts/sign_up.html
{% extends 'base.html' %}

{%block title%}
<title>sign up page</title>
{%endblock%}

{%block main%}

{% if error %}
<p>{{ error }}</p>
{% endif %}

<form action = "{% url 'my_accounts:sign_up' %}" method='POST'>
    {% csrf_token %}
    {% comment %} forbiden 403 error 대비 - form tag안에 작성. {% endcomment %}
    <div>
        <input type = 'text' name = 'username' placeholder='Your ID'/>
    </div>
    <div>
        <input type = 'password' name = 'password' placeholder='Your Password'/>
    </div>
    <div>
        <input type = 'password' name = 'password_check' placeholder='check your password'/>
    </div>
    <button type = 'submit'>회원가입</button>
</form>

<h1>This is sign up page</h1>
{%endblock%}