blog/urls.py
from django.urls import path, include # include 함수로 landing에 연결을 해줄 수 있음.
from . import views # 상대경로로 저장을 해 줘야 함.

app_name = "blog"
urlpatterns = [
    path('',views.index), # 아무것도 입력안했을 때, views의 index를 실행시켜준다.
    path('second/',views.article),
    path('post-write/', views.blog_post_write),
    path('home/', views.blog_home, name="home"),
    path('post-view/<int:post_id>/', views.blog_post_view, name="detail"),
    path('post-edit/<int:post_id>/', views.blog_post_update),
    path('post-delete/<int:post_id>/',views.blog_post_delete),
]

django_demo/urls.py
from django.contrib import admin
from django.urls import path, include # include 함수로 landing에 연결을 해줄 수 있음.
from django.conf import settings
from django.conf.urls.static import static
from . import views # 상대경로로 저장을 해 줘야 함.


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('landing/',include('landing.urls')),
    path('blog/',include('blog.urls')),
    path('blog_samples/',include('blog_samples.urls')),
    path('my_accounts/', include('my_accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

my_accounts/urls.py
from django.urls import path
from my_accounts import views

app_name='my_accounts'

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name = 'logout')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title%}
    {% endblock %}
  </head>
  <body>
    <nav>
      <span><a href="{% url "blog:home" %}">blog</a></span>
      {%if not user.is_authenticated%}
      <span><a href="{% url "my_accounts:login" %}">login</a></span>
      {%else%}
      <span>
        <form action = '{% url 'my_accounts:logout' %}' method = 'post'>
          {% csrf_token %}
          <button type = 'submit'>log-out</button>
        </form>
      </span>
      {%endif%}
    </nav>
    {% block main %}
    {% endblock %}
    <footer> 푸터 입니다. </footer>
  </body>
</html>