blog/urls.py
from django.urls import path, include # include 함수로 landing에 연결을 해줄 수 있음.
from . import views # 상대경로로 저장을 해 줘야 함.

app_name = "blog"
urlpatterns = [
    path('',views.index), # 아무것도 입력안했을 때, views의 index를 실행시켜준다.
    path('second/',views.article),
    path('post-write/', views.blog_post_write),
    path('home/', views.blog_home, name="home"),
    path('post-view/<int:post_id>/', views.blog_post_view, name="detail"),
    path('post-edit/<int:post_id>/', views.blog_post_update),
    path('post-delete/<int:post_id>/',views.blog_post_delete),
]

blog_samples/urls.py
from django.urls import path
from . import views


from blog_samples import views
app_name="blog_samples"
urlpatterns = [
    path('', views.index, name="home"),
    path('post/', views.post, name="post"),
    path('about/', views.contact, name="contact"),
]

django_demo/urls.py
from django.contrib import admin
from django.urls import path, include # include 함수로 landing에 연결을 해줄 수 있음.
from django.conf import settings
from django.conf.urls.static import static
from . import views # 상대경로로 저장을 해 줘야 함.


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('landing/',include('landing.urls')),
    path('blog/',include('blog.urls')),
    path('blog_samples/',include('blog_samples.urls')),
    path('my_accounts/', include('my_accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

my_accounts/urls.py
from django.urls import path
from my_accounts import views

app_name='my_accounts'

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name = 'logout')
]

blog_samples/models.py
from django.db import models

# Create your models here.

blog_samples/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
# Create your views here.
def index(request):
    
        return render(request, "blog_samples/index.html")
    



def post(request):
    if request.user.is_authenticated:
        return render(request, "blog_samples/post.html")
    else :
        return redirect("my_accounts:login")

def contact(request): 
    return render(request, "blog_samples/contact.html")

blog_samples/templates/blog_samples/about.html
{% extends "blog_samples/base.html" %} {% block header %}


{% block header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}
        <!-- Main Content-->
{% block main %}
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

blog_samples/templates/blog_samples/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "blog_samples/css/styles.css" %}" rel="stylesheet"/>
        {% block css %}
        {% endblock %}
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "blog_samples:home" %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "blog_samples:contact" %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "blog_samples:post" %}">Post for users</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "my_accounts:logout" %}">Log out</a>
                        </form></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "my_accounts:login" %}">login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        {% block header %}
        {% endblock%}
        <!-- Main Content-->
        {% block main %}
        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog_samples/templates/blog_samples/contact.html
{% extends "blog_samples/base.html" %} 
{% block header %}
<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('assets/img/contact-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Contact Me</h1>
          <span class="subheading">Have questions? I have answers.</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}
<!-- Main Content-->
{% block main %}
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p
          >Want to get in touch? Fill out the form below to send me a message
          and I will get back to you as soon as possible!</p
        >
        <div class="my-5">
          <!-- * * * * * * * * * * * * * * *-->
          <!-- * * SB Forms Contact Form * *-->
          <!-- * * * * * * * * * * * * * * *-->
          <!-- This form is pre-integrated with SB Forms.-->
          <!-- To make this form functional, sign up at-->
          <!-- https://startbootstrap.com/solution/contact-forms-->
          <!-- to get an API token!-->
          <form id="contactForm" data-sb-form-api-token="API_TOKEN">
            <div class="form-floating">
              <input
                class="form-control"
                id="name"
                type="text"
                placeholder="Enter your name..."
                data-sb-validations="required"
              />
              <label for="name">Name</label>
              <div class="invalid-feedback" data-sb-feedback="name:required"
                >A name is required.</div
              >
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="email"
                type="email"
                placeholder="Enter your email..."
                data-sb-validations="required,email"
              />
              <label for="email">Email address</label>
              <div class="invalid-feedback" data-sb-feedback="email:required"
                >An email is required.</div
              >
              <div class="invalid-feedback" data-sb-feedback="email:email"
                >Email is not valid.</div
              >
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="phone"
                type="tel"
                placeholder="Enter your phone number..."
                data-sb-validations="required"
              />
              <label for="phone">Phone Number</label>
              <div class="invalid-feedback" data-sb-feedback="phone:required"
                >A phone number is required.</div
              >
            </div>
            <div class="form-floating">
              <textarea
                class="form-control"
                id="message"
                placeholder="Enter your message here..."
                style="height: 12rem"
                data-sb-validations="required"
              ></textarea>
              <label for="message">Message</label>
              <div class="invalid-feedback" data-sb-feedback="message:required"
                >A message is required.</div
              >
            </div>
            <br />
            <!-- Submit success message-->
            <!---->
            <!-- This is what your users will see when the form-->
            <!-- has successfully submitted-->
            <div class="d-none" id="submitSuccessMessage">
              <div class="text-center mb-3">
                <div class="fw-bolder">Form submission successful!</div>
                To activate this form, sign up at
                <br />
                <a href="https://startbootstrap.com/solution/contact-forms"
                  >https://startbootstrap.com/solution/contact-forms</a
                >
              </div>
            </div>
            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage"
              ><div class="text-center text-danger mb-3"
                >Error sending message!</div
              ></div
            >
            <!-- Submit Button-->
            <button
              class="btn btn-primary text-uppercase disabled"
              id="submitButton"
              type="submit"
              >Send</button
            >
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

blog_samples/templates/blog_samples/index.html
{% extends "blog_samples/base.html" %}

<!-- Page Header-->
{% block header %}
<header
  class="masthead"
  style="background-image: url('assets/img/home-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}
<!-- Main Content-->
{% block main %}
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      <div class="post-preview">
        <a href="post.html">
          <h2 class="post-title"
            >Man must explore, and this is exploration at its greatest</h2
          >
          <h3 class="post-subtitle"
            >Problems look mighty small from 150 miles up</h3
          >
        </a>
        <p class="post-meta">
          Posted by
          <a href="#!">Start Bootstrap</a>
          on September 24, 2022
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      <!-- Post preview-->
      <div class="post-preview">
        <a href="post.html"
          ><h2 class="post-title"
            >I believe every human has a finite number of heartbeats. I don't
            intend to waste any of mine.</h2
          ></a
        >
        <p class="post-meta">
          Posted by
          <a href="#!">Start Bootstrap</a>
          on September 18, 2022
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      <!-- Post preview-->
      <div class="post-preview">
        <a href="post.html">
          <h2 class="post-title">Science has not yet mastered prophecy</h2>
          <h3 class="post-subtitle"
            >We predict too much for the next year and yet far too little for
            the next ten.</h3
          >
        </a>
        <p class="post-meta">
          Posted by
          <a href="#!">Start Bootstrap</a>
          on August 24, 2022
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      <!-- Post preview-->
      <div class="post-preview">
        <a href="post.html">
          <h2 class="post-title">Failure is not an option</h2>
          <h3 class="post-subtitle"
            >Many say exploration is part of our destiny, but it’s actually our
            duty to future generations.</h3
          >
        </a>
        <p class="post-meta">
          Posted by
          <a href="#!">Start Bootstrap</a>
          on July 8, 2022
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      <!-- Pager-->
      <div class="d-flex justify-content-end mb-4"
        ><a class="btn btn-primary text-uppercase" href="#!"
          >Older Posts →</a
        ></div
      >
    </div>
  </div>
</div>
{% endblock %}
<!-- Footer-->

blog_samples/templates/blog_samples/post.html
{% extends "blog_samples/base.html" %} 
{% block header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>Man must explore, and this is exploration at its greatest</h1>
                            <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                            <span class="meta">
                                Posted by
                                <a href="#!">Start Bootstrap</a>
                                on August 24, 2022
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}
        <!-- Post Content-->
{% block main %}
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>
                        <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                        <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>
                        <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>
                        <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>
                        <h2 class="section-heading">The Final Frontier</h2>
                        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                        <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
                        <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>
                        <h2 class="section-heading">Reaching for the Stars</h2>
                        <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>
                        <a href="#!"><img class="img-fluid" src="assets/img/post-sample-image.jpg" alt="..." /></a>
                        <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                        <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>
                        <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
                        <p>
                            Placeholder text by
                            <a href="http://spaceipsum.com/">Space Ipsum</a>
                            &middot; Images by
                            <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                        </p>
                    </div>
                </div>
            </div>
        </article>
    {% endblock %}
        <!-- Footer-->